from __future__ import annotations

from functools import lru_cache
from pathlib import Path

from pydantic_settings import BaseSettings, SettingsConfigDict


class Settings(BaseSettings):
    model_config = SettingsConfigDict(env_file=".env", env_prefix="IVQC_", extra="ignore")

    app_name: str = "industrial-vision-qc-backend"
    environment: str = "development"
    log_level: str = "INFO"

    database_url: str = "postgresql+asyncpg://vision_qc:vision_qc@127.0.0.1:5432/industrialvision_dev"
    inference_service_url: str = "http://127.0.0.1:8100"
    inference_timeout_seconds: float = 30.0
    max_upload_bytes: int = 10 * 1024 * 1024

    storage_dir: str = "storage-images"
    default_rule_version: int = 1

    # ---- Phase 7 industrial integration ----
    # Disabled by default: the development environment runs in
    # NOT_INTEGRATED (the desired command is computed and recorded, the PLC
    # adapter is never invoked, and no field state is claimed). Industrial
    # integration is OPT-IN: set IVQC_PLC_ENABLED=true (and run the PLC
    # simulator/gateway) and IVQC_MES_ENABLED=true to enable the closed loop.
    plc_url: str = "http://127.0.0.1:8501"
    plc_adapter_type: str = "http"  # "http" | "opcua"
    plc_opcua_endpoint: str = "opc.tcp://127.0.0.1:8503"
    plc_timeout_seconds: float = 2.0
    plc_max_retries: int = 2
    plc_enabled: bool = False
    mes_url: str = "http://127.0.0.1:8502"
    mes_timeout_seconds: float = 2.0
    mes_max_retries: int = 2
    mes_enabled: bool = False

    # ---- Phase 9 Quality Copilot (LLM provider) ----
    # OpenAI-compatible endpoint. The API key MUST come from the environment
    # (never from git). llm_provider="fake" runs the deterministic offline
    # FakeLlmProvider (tests / no paid API); llm_provider="openai" uses the
    # configured OpenAI-compatible endpoint.
    llm_provider: str = "fake"  # "fake" | "openai"
    llm_base_url: str = "http://127.0.0.1:11434/v1"  # e.g. local vLLM/Ollama
    llm_model: str = "qwen2.5-7b-instruct"
    llm_api_key: str = ""
    llm_timeout_seconds: float = 30.0
    llm_max_tool_calls: int = 6
    llm_max_turns: int = 3

    # ---- Model governance trust boundary (fail-closed) ----
    # Every governance mutation requires an authenticated principal. With no
    # credential store configured the store is empty and every protected
    # endpoint answers 401: there is no "anonymous admin" fallback.
    # JSON object: {"<token>": {"subject": "...", "roles": ["engineer"]}}
    api_tokens: str = ""
    # Optional file alternative (preferred in production: keeps tokens out of
    # the process environment and out of `docker inspect`).
    api_tokens_file: str = ""

    # HMAC secret shared with the trusted training/eval pipeline. The pipeline
    # signs {model identity, artifact hash, metrics, domain evidence} with it;
    # without a configured secret the attestation endpoint refuses to run.
    pipeline_hmac_secret: str = ""
    attestation_max_skew_seconds: int = 300

    # Acceptance thresholds are server-owned state, never request payload.
    promotion_policy_path: str = "backend/config/promotion_policy.yaml"
    # When set, the policy file must hash to this value or every gate fails.
    promotion_policy_sha256: str = ""

    deployment_manifest_path: str = "backend/config/deployment_manifest.yaml"
    # Generated by POST /api/v1/models/{id}/activate. Read by the inference
    # service through IVQC_MANIFEST and IVQC_WEIGHTS / IVQC_PATCHCORE_BANK.
    runtime_env_file: str = "inference-service/.env.runtime"

    # Repository root used to resolve every relative artifact URI. Empty means
    # "derive from this file's location".
    project_root: str = ""


@lru_cache
def get_settings() -> Settings:
    return Settings()


def project_root() -> Path:
    """Repository root. Every relative artifact / config URI resolves here."""
    configured = get_settings().project_root
    if configured:
        return Path(configured).resolve()
    return Path(__file__).resolve().parents[2]


def resolve_path(value: str | Path) -> Path:
    """Resolve a configured path against the project root (absolute wins)."""
    p = Path(value)
    return p if p.is_absolute() else (project_root() / p).resolve()
